### ISSUE TITLE
Error loading module 'hs.axuielement.internal' from file internal.so

### ISSUE THREAD

**Issue by realav** [asmagill/hs._asm.axuielement#22] opened 2020-08-29 10:47 UTC
I got this error...

`2020-08-29 13:25:20: -- Lazy extension loading enabled 2020-08-29 13:25:20: -- Loading ~/.hammerspoon/init.lua 2020-08-29 13:25:20: *** ERROR: error loading module 'hs.axuielement.internal' from file '/Users/xxx/.hammerspoon/hs/axuielement/internal.so': dlopen(/Users/xxx/.hammerspoon/hs/axuielement/internal.so, 6): Symbol not found: _lua_newuserdatauv Referenced from: /Users/xxx/.hammerspoon/hs/axuielement/internal.so Expected in: /Applications/Hammerspoon.app/Contents/MacOS/../Frameworks/LuaSkin.framework/Versions/A/LuaSkin in /Users/xxx/.hammerspoon/hs/axuielement/internal.so stack traceback: [C]: in ? [C]: in function 'rawrequire' ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require' /Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua:46: in main chunk [C]: in function 'rawrequire' ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require' /Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk [C]: in function 'rawrequire' ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require' /Users/xxx/.hammerspoon/init.lua:1: in main chunk [C]: in function 'xpcall' ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup' (...tail calls...)`

**Comment by asmagill** [comment] 2020-08-29 17:54
We're kind of in a transition period with Hammerspoon... there are kind of three versions being used right now and which you are using determines which precompiled binary (if one has been made yet) you should use...

1) the official release is based off of Lua 5.3 and does not properly support coroutines that utilize Hammerspoon specific additions... unfortunately no precompiled binary of this module exists for this at the moment, though I'll try to address this in the next day or so -- I have to downgrade my installation to build it.

2) A fix was implemented for coroutines and Hammerspoon extensions a few months ago and applied to the master branch, but still was based on Lua 5.3 -- if you're running a development build of Hammerspoon from this time period, you should use `axuielement-v1.0.7.2.tar.gz`

3) the latest and greatest in the Hammerspoon master branch has been migrated to Lua 5.4 (along with the coroutine fixes) -- if you're using a recent development build of Hammerspoon, you should use `axuielement-v1.0.7.3.tar.gz`

Of course you can always clone the repository and build axuielement yourself against your own Hammerspoon installation (to build this module just requires that you have Apple's XCode installed and then clone this repo -- you don't have to have the Hammerspoon repo cloned unless you want to build a development version of it as well).

Unless you inform me otherwise, I'm going to assume that you're running the official release of Hammerspoon...  As stated above, I should be able to get a precompiled version that works with it uploaded in the next day or so and will post here when it's available.

**Comment by realav** [comment] 2020-08-30 11:39
After using axuielement-v1.0.7.2.tar.gz I got this...

`2020-08-30 17:05:18: -- Lazy extension loading enabled
2020-08-30 17:05:18: -- Loading ~/.hammerspoon/init.lua
2020-08-30 17:05:18: *** ERROR: NSInvalidArgumentException: +[LuaSkin sharedWithState:]: unrecognized selector sent to class 0x109416e30
(
	0   CoreFoundation                      0x00007fff337b1b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c5fa5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff33830b37 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff337163bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff33715d98 _CF_forwarding_prep_0 + 120
	5   internal.so                         0x000000010c2cc707 luaopen_hs_axuielement_internal + 39
	6   LuaSkin                             0x0000000109402024 luaD_precall + 681
	7   LuaSkin                             0x0000000109402186 luaD_call + 52
	8   LuaSkin                             0x00000001094021d3 luaD_callnoyield + 21
	9   LuaSkin                             0x00000001093fbcea lua_callk + 132
	10  LuaSkin                             0x00000001093ef9a4 ll_require + 447
	11  LuaSkin                             0x0000000109402024 luaD_precall + 681
	12  LuaSkin                             0x00000001093fe1d4 luaV_execute + 708
	13  LuaSkin                             0x0000000109402192 luaD_call + 64
	14  LuaSkin                             0x00000001094021d3 luaD_callnoyield + 21
	15  LuaSkin                             0x00000001093fbcea lua_callk + 132
	16  LuaSkin                             0x00000001093ef9a4 ll_require + 447
	17  LuaSkin                             0x0000000109402024 luaD_precall + 681
	18  LuaSkin                             0x00000001093fe1d4 luaV_execute + 708
	19  LuaSkin                             0x0000000109402192 luaD_call + 64
	20  LuaSkin                             0x00000001094021d3 luaD_callnoyield + 21
	21  LuaSkin                             0x00000001093fbcea lua_callk + 132
	22  LuaSkin                             0x00000001093ef9a4 ll_require + 447
	23  LuaSkin                             0x0000000109402024 luaD_precall + 681
	24  LuaSkin                             0x00000001093fe1d4 luaV_execute + 708
	25  LuaSkin                             0x0000000109402192 luaD_call + 64
	26  LuaSkin                             0x00000001094021d3 luaD_callnoyield + 21
	27  LuaSkin                             0x00000001093edfd2 luai_objcttry + 28
	28  LuaSkin                             0x00000001094026d0 luaD_pcall + 110
	29  LuaSkin                             0x00000001093fbe20 lua_pcallk + 236
	30  LuaSkin                             0x00000001094015ae luaB_xpcall + 115
	31  LuaSkin                             0x0000000109402024 luaD_precall + 681
	32  LuaSkin                             0x00000001093fe1d4 luaV_execute + 708
	33  LuaSkin                             0x0000000109402192 luaD_call + 64
	34  LuaSkin                             0x00000001094021d3 luaD_callnoyield + 21
	35  LuaSkin                             0x00000001093edfd2 luai_objcttry + 28
	36  LuaSkin                             0x00000001094026d0 luaD_pcall + 110
	37  LuaSkin                             0x00000001093fbe20 lua_pcallk + 236
	38  Hammerspoon                         0x00000001090bf852 MJLuaInit + 2189
	39  Hammerspoon                         0x00000001090bee9c MJLuaCreate + 14
	40  Hammerspoon                         0x00000001090bbc23 -[MJAppDelegate applicationDidFinishLaunching:] + 2934
	41  CoreFoundation                      0x00007fff3372b80f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	42  CoreFoundation                      0x00007fff3372b7a3 ___CFXRegistrationPost1_block_invoke + 63
	43  CoreFoundation                      0x00007fff3372b718 _CFXRegistrationPost1 + 372
	44  CoreFoundation                      0x00007fff3372b384 ___CFXNotificationPost_block_invoke + 80
	45  CoreFoundation                      0x00007fff336fb4fd -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
	46  CoreFoundation                      0x00007fff336fa9a9 _CFXNotificationPost + 1351
	47  Foundation                          0x00007fff35d78786 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	48  AppKit                              0x00007fff309af4f3 -[NSApplication _postDidFinishNotification] + 312
	49  AppKit                              0x00007fff309af232 -[NSApplication _sendFinishLaunchingNotification] + 208
	50  AppKit                              0x00007fff309ac2f3 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 549
	51  AppKit                              0x00007fff309abf38 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 688
	52  Foundation                          0x00007fff35da3a26 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
	53  Foundation                          0x00007fff35da3890 _NSAppleEventManagerGenericHandler + 98
	54  AE                                  0x00007fff34aa8203 _AppleEventsCheckInAppWithBlock + 18103
	55  AE                                  0x00007fff34aa7929 _AppleEventsCheckInAppWithBlock + 15837
	56  AE                                  0x00007fff34a9fbd7 aeProcessAppleEvent + 449
	57  HIToolbox                           0x00007fff323727fa AEProcessAppleEvent + 54
	58  AppKit                              0x00007fff309a62d1 _DPSNextEvent + 1547
	59  AppKit                              0x00007fff309a4880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	60  AppKit                              0x00007fff3099658e -[NSApplication run] + 658
	61  AppKit                              0x00007fff30968396 NSApplicationMain + 777
	62  libdyld.dylib                       0x00007fff6d7a2cc9 start + 1
	63  ???                                 0x0000000000000001 0x0 + 1
)
`

**Comment by asmagill** [comment] 2020-08-30 16:55
Which tells me that you're running the official 0.9.78 release, so you'll need the version I just uploaded, `axuielement-v1.0.7.2.release.tar.gz` at https://github.com/asmagill/hs._asm.axuielement/blob/master/axuielement-v1.0.7.2.release.tar.gz.

Let me know if you have any additional issues!

**Comment by realav** [comment] 2020-08-30 18:39
Now I got this...
I am not sure if it's related to hs.axuielement but I am trying to run this plugin:
[https://github.com/szymonkaliski/hhtwm](https://github.com/szymonkaliski/hhtwm)

`2020-08-30 23:57:40: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-08-30 23:57:40: -- Lazy extension loading enabled
2020-08-30 23:57:40: -- Loading ~/.hammerspoon/init.lua
2020-08-30 23:57:40: -- Loading extension: uielement
2020-08-30 23:57:40: -- Loading extension: logger
2020-08-30 23:57:40: -- Loading extension: settings
2020-08-30 23:57:40: 23:57:40      hhtwm:     reading from hs.settings
2020-08-30 23:57:40: -- Loading extension: window
2020-08-30 23:57:40: -- Loading extensions: window.filter
2020-08-30 23:57:40: -- Loading extension: screen
2020-08-30 23:57:40: -- Loading extension: mouse
2020-08-30 23:57:40: -- Loading extension: fnutils
2020-08-30 23:57:40: *** ERROR: NSInvalidArgumentException: *** +[NSString stringWithUTF8String:]: NULL cString
(
	0   CoreFoundation                      0x00007fff337b1b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c5fa5bf objc_exception_throw + 48
	2   Foundation                          0x00007fff35d93af9 +[NSString stringWithUTF8String:] + 174
	3   LuaSkin                             0x00000001065d7d4c -[LuaSkin toNSObjectAtIndex:withOptions:alreadySeenObjects:] + 1474
	4   LuaSkin                             0x00000001065d42e4 -[LuaSkin toNSObjectAtIndex:withOptions:] + 80
	5   internal.so                         0x0000000109ca7c40 axuielement_getWindowElement + 112
	6   LuaSkin                             0x00000001065ef024 luaD_precall + 681
	7   LuaSkin                             0x00000001065eb157 luaV_execute + 583
	8   LuaSkin                             0x00000001065ef192 luaD_call + 64
	9   LuaSkin                             0x00000001065ef1d3 luaD_callnoyield + 21
	10  LuaSkin                             0x00000001065dafd2 luai_objcttry + 28
	11  LuaSkin                             0x00000001065ef6d0 luaD_pcall + 110
	12  LuaSkin                             0x00000001065e8e20 lua_pcallk + 236
	13  LuaSkin                             0x00000001065ee5ae luaB_xpcall + 115
	14  LuaSkin                             0x00000001065ef024 luaD_precall + 681
	15  LuaSkin                             0x00000001065eb1d4 luaV_execute + 708
	16  LuaSkin                             0x00000001065ef192 luaD_call + 64
	17  LuaSkin                             0x00000001065ef1d3 luaD_callnoyield + 21
	18  LuaSkin                             0x00000001065dafd2 luai_objcttry + 28
	19  LuaSkin                             0x00000001065ef6d0 luaD_pcall + 110
	20  LuaSkin                             0x00000001065e8e20 lua_pcallk + 236
	21  Hammerspoon                         0x00000001062ac852 MJLuaInit + 2189
	22  Hammerspoon                         0x00000001062abe9c MJLuaCreate + 14
	23  Hammerspoon                         0x00000001062a8c23 -[MJAppDelegate applicationDidFinishLaunching:] + 2934
	24  CoreFoundation                      0x00007fff3372b80f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	25  CoreFoundation                      0x00007fff3372b7a3 ___CFXRegistrationPost1_block_invoke + 63
	26  CoreFoundation                      0x00007fff3372b718 _CFXRegistrationPost1 + 372
	27  CoreFoundation                      0x00007fff3372b384 ___CFXNotificationPost_block_invoke + 80
	28  CoreFoundation                      0x00007fff336fb4fd -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
	29  CoreFoundation                      0x00007fff336fa9a9 _CFXNotificationPost + 1351
	30  Foundation                          0x00007fff35d78786 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	31  AppKit                              0x00007fff309af4f3 -[NSApplication _postDidFinishNotification] + 312
	32  AppKit                              0x00007fff309af232 -[NSApplication _sendFinishLaunchingNotification] + 208
	33  AppKit                              0x00007fff309ac2f3 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 549
	34  AppKit                              0x00007fff309abf38 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 688
	35  Foundation                          0x00007fff35da3a26 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
	36  Foundation                          0x00007fff35da3890 _NSAppleEventManagerGenericHandler + 98
	37  AE                                  0x00007fff34aa8203 _AppleEventsCheckInAppWithBlock + 18103
	38  AE                                  0x00007fff34aa7929 _AppleEventsCheckInAppWithBlock + 15837
	39  AE                                  0x00007fff34a9fbd7 aeProcessAppleEvent + 449
	40  HIToolbox                           0x00007fff323727fa AEProcessAppleEvent + 54
	41  AppKit                              0x00007fff309a62d1 _DPSNextEvent + 1547
	42  AppKit                              0x00007fff309a4880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	43  AppKit                              0x00007fff3099658e -[NSApplication run] + 658
	44  AppKit                              0x00007fff30968396 NSApplicationMain + 777
	45  libdyld.dylib                       0x00007fff6d7a2cc9 start + 1
	46  ???                                 0x0000000000000001 0x0 + 1
)
2020-08-30 23:57:40: ********
2020-08-30 23:57:40: 23:57:40 ERROR:   LuaSkin: hs.application.watcher callback: NSInvalidArgumentException: *** +[NSString stringWithUTF8String:]: NULL cString
(
	0   CoreFoundation                      0x00007fff337b1b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c5fa5bf objc_exception_throw + 48
	2   Foundation                          0x00007fff35d93af9 +[NSString stringWithUTF8String:] + 174
	3   LuaSkin                             0x00000001065d7d4c -[LuaSkin toNSObjectAtIndex:withOptions:alreadySeenObjects:] + 1474
	4   LuaSkin                             0x00000001065d42e4 -[LuaSkin toNSObjectAtIndex:withOptions:] + 80
	5   internal.so                         0x0000000109ca7c40 axuielement_getWindowElement + 112
	6   LuaSkin                             0x00000001065ef024 luaD_precall + 681
	7   LuaSkin                             0x00000001065eb157 luaV_execute + 583
	8   LuaSkin                             0x00000001065ef192 luaD_call + 64
	9   LuaSkin                             0x00000001065ef1d3 luaD_callnoyield + 21
	10  LuaSkin                             0x00000001065dafd2 luai_objcttry + 28
	11  LuaSkin                             0x00000001065ef6d0 luaD_pcall + 110
	12  LuaSkin                             0x00000001065e8e20 lua_pcallk + 236
	13  LuaSkin                             0x00000001065d1a18 -[LuaSkin protectedCallAndTraceback:nresults:] + 203
	14  LuaSkin                             0x00000001065d1acd -[LuaSkin protectedCallAndError:nargs:nresults:] + 55
	15  watcher.so                          0x0000000109cd3050 -[AppWatcher callback:withEvent:] + 578
	16  watcher.so                          0x0000000109cd327d -[AppWatcher applicationActivated:] + 65
	17  CoreFoundation                      0x00007fff3372b80f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	18  CoreFoundation                      0x00007fff3372b7a3 ___CFXRegistrationPost1_block_invoke + 63
	19  CoreFoundation                      0x00007fff3372b718 _CFXRegistrationPost1 + 372
	20  CoreFoundation                      0x00007fff3372b384 ___CFXNotificationPost_block_invoke + 80
	21  CoreFoundation                      0x00007fff336fb4fd -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
	22  CoreFoundation                      0x00007fff336fa9a9 _CFXNotificationPost + 1351
	23  Foundation                          0x00007fff35d78786 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	24  AppKit                              0x00007fff30bdf2c6 applicationStatusSubsystemCallback + 736
	25  LaunchServices                      0x00007fff34e8b86e ___LSScheduleNotificationFunction_block_invoke_2 + 47
	26  CoreFoundation                      0x00007fff337359ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	27  CoreFoundation                      0x00007fff33735934 __CFRunLoopDoBlocks + 379
	28  CoreFoundation                      0x00007fff3373482b __CFRunLoopRun + 912
	29  CoreFoundation                      0x00007fff33733e3e CFRunLoopRunSpecific + 462
	30  HIToolbox                           0x00007fff32360abd RunCurrentEventLoopInMode + 292
	31  HIToolbox                           0x00007fff323606f4 ReceiveNextEventCommon + 359
	32  HIToolbox                           0x00007fff32360579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	33  AppKit                              0x00007fff309a6039 _DPSNextEvent + 883
	34  AppKit                              0x00007fff309a4880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	35  AppKit                              0x00007fff3099658e -[NSApplication run] + 658
	36  AppKit                              0x00007fff30968396 NSApplicationMain + 777
	37  libdyld.dylib                       0x00007fff6d7a2cc9 start + 1
	38  ???                                 0x0000000000000001 0x0 + 1
)
2020-08-30 23:57:40: ********
2020-08-30 23:57:45: 23:57:45 ** Warning:   wfilter: No accessibility access to app Mail Networking (no watcher pid)`

**Comment by asmagill** [comment] 2020-08-30 22:51
Crap, apparently the rewrite for `hs.application` and `hs.window` has also been since the last release as well... When I built the version I asked you to try, I just confirmed that it compiled and loaded, I didn't run any deep tests.

I'll need to dig into the history for this repo and pull an earlier conversion function... I'll try and get it taken care of tonight and get a tested build out by morning.

**Comment by latenitefilms** [comment] 2020-08-30 23:31
At this point it's probably easier to just build your own Hammerspoon build rather than try and make these extensions work. Alternatively, you could use the latest [CommandPost](commandpost.io) beta which has a working AX extension inside.

**Comment by asmagill** [comment] 2020-08-31 07:36
Ok, `axuielement-v1.0.7.3.release.tar.gz` at https://github.com/asmagill/hs._asm.axuielement/blob/master/axuielement-v1.0.7.3.release.tar.gz should work... I've minimally tested it with converting `hs.window` and `hs.application` objects back and forth with their `hs.axuielement` equivalents, and will do some further testing tomorrow, but from the error messages you've shared, I'm pretty sure this should address them.

@cmsj, we really need to decide when we're going to commit the current master to a release as it has a *lot* of changes underneath the hood that are requiring workarounds like this for 3rd party module developers (which may mean primarily me, but still...)

I'm not saying land whats there ATM, as I really want `hs.axuielement` to be a part of it, but we need to set a cut-off date... once you let me know what works for you and your changes to `hs.application` and `hs.window`, I'll make sure `hs.axuielement` at least is ready.

**Comment by latenitefilms** [comment] 2020-08-31 08:59
@asmagill & @cmsj - Another option could be to explore a previously discussed idea of having public daily or beta builds for Hammerspoon?

**Comment by cmsj** [comment] 2020-08-31 09:14
@asmagill how extensive are the axuielement changes you want to make? We could merge it and then make the final adjustments on master?

The only thing that's *really* blocking a release from my side is the weirdness I wasn't able to track down in hs.application when initialising an object from a PID.

**Comment by latenitefilms** [comment] 2020-08-31 09:19
> The only thing that's really blocking a release from my side is the weirdness I wasn't able to track down in hs.application when initialising an object from a PID.

I'm still seeing a few of these errors - but I reckon it might be a timing issue. I reckon Hammerspoon/CommandPost is busy processing Lua code, and by the time it gets to processing the `hs.application` stuff, the app has already closed, etc. However, everything still seems to be working correctly - I haven't noticed any deal breaking issues in CommandPost (which is in-sync with Hammerspoon - except we're running some more up-to-date pods).

**Comment by realav** [comment] 2020-08-31 09:36
Looks like axuielement issue is fixed with `axuielement-v1.0.7.3.release.tar.gz` but still getting errors...

`2020-08-31 14:57:32: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-08-31 14:57:32: -- Lazy extension loading enabled
2020-08-31 14:57:33: -- Loading ~/.hammerspoon/init.lua
2020-08-31 14:57:33: -- Loading extension: uielement
2020-08-31 14:57:33: -- Loading extension: logger
2020-08-31 14:57:33: -- Loading extension: settings
2020-08-31 14:57:33: 14:57:33      hhtwm:     reading from hs.settings
2020-08-31 14:57:33: -- Loading extension: window
2020-08-31 14:57:33: -- Loading extensions: window.filter
2020-08-31 14:57:33: -- Loading extension: screen
2020-08-31 14:57:33: -- Loading extension: mouse
2020-08-31 14:57:33: -- Loading extension: fnutils
2020-08-31 14:57:33: -- Loading extension: drawing
2020-08-31 14:57:33: *** ERROR: /Users/xxx/.hammerspoon/hhtwm/init.lua:628: attempt to concatenate a nil value (local 'layoutName')
stack traceback:
	/Users/xxx/.hammerspoon/hhtwm/init.lua:628: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:87: in function 'hs.fnutils.each'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:623: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:87: in function 'hs.fnutils.each'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:620: in function 'hhtwm.tile'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:796: in function 'hhtwm.start'
	/Users/xxx/.hammerspoon/init.lua:2: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
2020-08-31 14:57:33: ********
2020-08-31 14:57:33: 14:57:33 ERROR:   LuaSkin: hs.application.watcher callback: /Users/xxx/.hammerspoon/hhtwm/init.lua:628: attempt to concatenate a nil value (local 'layoutName')
stack traceback:
	/Users/xxx/.hammerspoon/hhtwm/init.lua:628: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:87: in function 'hs.fnutils.each'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:623: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:87: in function 'hs.fnutils.each'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:620: in function 'hhtwm.tile'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:944: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:982: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1004: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1029: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1397: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1202: in method 'getFocused'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1278: in function <...n.app/Contents/Resources/extensions/hs/window/filter.lua:1267>
	(...tail calls...)
2020-08-31 14:57:33: ********`

**Comment by szymonkaliski** [comment] 2020-08-31 12:20
@legendaryaman this one is coming from hhtwm - looks like something is wrong with layout naming - a bug in hhtwm most probably - feel free to create an issue on my repo and I'll try to get to it at some point (but heads up - super busy currently so might take a couple of weeks)

**Comment by realav** [comment] 2020-08-31 12:35
[HHTWM](https://github.com/szymonkaliski/hhtwm) [issue](https://github.com/asmagill/hs._asm.axuielement/issues/22#issuecomment-683674615) moved here: [https://github.com/szymonkaliski/hhtwm/issues/7](https://github.com/szymonkaliski/hhtwm/issues/7)

**Comment by asmagill** [comment] 2020-09-01 06:37
@cmsj, I need to review the pull to make sure it still matches what @latenitefilms and I have been using in our local builds, but the additions I still want to make are strictly with regards to helper functions that abstract some common chunks of likely repeated user code into a common library... I'm 99% sure that the additions I'm thinking of are strictly to the Lua code and can easily be added at any time later or even encapsulated into a single Lua file people can download independently if they need them before the subsequent release that includes them.

Give me till Wednesday and I'll be ready to merge the pull request.

If you need significantly longer to get window/application where you're comfortable, I may take a look at the settings/preferences/cfpreferences mix that we've talked about before and see how long I think it might take to get that ready for inclusion, but in the interest of having a stable(ish?) base going forward I have no problem with the preferences merger waiting for another version or two.

We're sitting on a release that includes your work on uielement/window/application, my work on coroutines, axuielement, and Lua 5.4, not to mention other bug fixes and documentation tweaks... we need it to land sooner rather than later.

**Comment by asmagill** [comment] 2020-09-01 06:47
@legendaryaman -- I agree this latest looks like an HHTWM issue (or something that HHTWM is using, other than axuielement). It's not something I've looked at before, but glancing at @szymonkaliski's repo, it looks interesting... if I get a chance to try it out and figure out anything before he gets a chance to look into the issue, I'll followup at the link he provided as well.

I'm going to close this because I think that the original issue has been addressed and @szymonkaliski has opened up a new issue at his repository for the latest issue, but feel free to re-open this if you think I'm mistaken. @cmsj, further discussion about the possible timing for 0.9.79 should probably continue at https://github.com/Hammerspoon/hammerspoon/pull/2373 or in a new issue about 0.9.79 specifically.

**Comment by latenitefilms** [comment] 2020-09-01 06:47
FWIW - I also believe `hs.serial` and `hs.websocket` are good to go too.

@asmagill - I'm using 0.7.6 of `hs._asm.axuielement`.

**Closed as completed by asmagill** 2020-09-01 06:47 UTC
